# Generated by Django 4.2.4 on 2023-08-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
