# Generated by Django 4.2.4 on 2023-10-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='server_response',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='MailingClient',
        ),
    ]
