# Generated by Django 4.2.4 on 2023-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_mailingclient_options_mailingsettings_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailingsettings',
            name='client',
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MailingClient',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.client', verbose_name='Клиент рассылки'),
        ),
    ]
