# Generated by Django 4.2.4 on 2023-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_emaillog_client_remove_mailingsettings_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='client',
            field=models.ManyToManyField(to='catalog.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(to='catalog.client', verbose_name='Клиент рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
